# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256, verbose_name='Коротка назва')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='Повна назва')),
            ],
            options={
                'verbose_name_plural': 'Підприємства',
                'verbose_name': 'Підприємство',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва країни')),
            ],
            options={
                'verbose_name_plural': 'Країни',
                'verbose_name': 'Країна',
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('source_info', models.TextField(verbose_name='Інфо про джерело')),
                ('talk_details', models.TextField(verbose_name='Інфо про розмову')),
                ('our_talk', models.BooleanField(default=False, verbose_name='Ми звернулися')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='talks_keeper.Company')),
            ],
            options={
                'verbose_name_plural': 'Розмови',
                'verbose_name': 'Розмова',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks_keeper.Country'),
        ),
    ]
