# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0002_auto_20161224_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='is_our_talk',
            field=models.BooleanField(default=False, verbose_name='Ми звернулися?'),
        ),
    ]
