# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0003_auto_20161225_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
