# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0004_auto_20170120_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='is_our_talk',
            field=models.BooleanField(default=False, verbose_name='Ми звернулися'),
        ),
    ]
