# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0005_auto_20170120_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Коротка назва'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Назва країни'),
        ),
    ]
