# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 20:05
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0006_auto_20170203_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Назва мітки')),
                ('color', colorfield.fields.ColorField(max_length=10, verbose_name='Колір')),
            ],
        ),
    ]
