# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0007_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='talks',
            field=models.ManyToManyField(to='talks_keeper.Talk'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Назва мітки'),
        ),
    ]
