# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks_keeper', '0008_auto_20170404_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name'], 'verbose_name': 'Мітка', 'verbose_name_plural': 'Мітки'},
        ),
        migrations.AlterField(
            model_name='label',
            name='talks',
            field=models.ManyToManyField(blank=True, to='talks_keeper.Talk'),
        ),
    ]
