# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Найменування')),
                ('part_number', models.CharField(blank=True, max_length=256, verbose_name='Індекс')),
                ('part_number2', models.CharField(blank=True, max_length=256, verbose_name='Наш індекс')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('notes', models.TextField(blank=True, verbose_name='Примітка')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненти',
            },
        ),
        migrations.CreateModel(
            name='ItemChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField()),
                ('changed_at', models.DateField(default=datetime.date.today, verbose_name='Дата зміни')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='items.Item')),
            ],
        ),
    ]
