# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['title'], 'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['title'], 'verbose_name': 'Інструмент', 'verbose_name_plural': 'Інструменти'},
        ),
    ]
