# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemchange',
            old_name='current_quantity',
            new_name='current',
        ),
    ]
