# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20160731_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchange',
            options={'verbose_name': 'Зміна кількості', 'verbose_name_plural': 'Зміни кількості'},
        ),
    ]
