# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_order_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='ready',
        ),
    ]
