# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20160731_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemchange',
            old_name='current_quantity',
            new_name='additional_quantity',
        ),
    ]
