# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20161019_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(blank=True, verbose_name='Норма витрати, м'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, verbose_name='Вага, кг'),
        ),
    ]
