# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20160731_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchange',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
    ]
