# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20161101_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Виріб', 'verbose_name_plural': 'Вироби'},
        ),
    ]
