# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemchange_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchange',
            name='additional_quantity',
            field=models.FloatField(),
        ),
    ]
