# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20160823_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Найменування')),
                ('part_number', models.CharField(blank=True, max_length=256, verbose_name='Індекс')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('notes', models.TextField(blank=True, verbose_name='Примітка')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='items.Product'),
        ),
    ]
