# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_category_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='critical_qty',
            field=models.FloatField(default=0, verbose_name='Критична кількість'),
        ),
        migrations.AddField(
            model_name='material',
            name='critical_qty',
            field=models.FloatField(default=0, verbose_name='Критична кількість'),
        ),
        migrations.AddField(
            model_name='tool',
            name='critical_qty',
            field=models.FloatField(default=0, verbose_name='Критична кількість'),
        ),
    ]
