# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20160828_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256, verbose_name='Замовник')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Дата зміни')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='items.Order')),
            ],
            options={
                'verbose_name': 'Поле замовлення',
                'verbose_name_plural': 'Поля замовлення',
            },
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненти'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Позиція на складі', 'verbose_name_plural': 'Позиції на складі'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Виріб', 'verbose_name_plural': 'Вироби'},
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product'),
        ),
    ]
