# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20161122_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ready',
            new_name='is_ready',
        ),
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Готовність замовлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_notes',
            field=models.TextField(null=True, verbose_name='Дані про відправлення'),
        ),
    ]
