# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20161127_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Замовлення готове'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Замовлення відправлено'),
        ),
    ]
