# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20161204_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Замовлення оплачено'),
        ),
    ]
