# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20161212_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.Category', verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
