# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20170117_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_qty_update',
        ),
        migrations.RemoveField(
            model_name='item',
            name='previous_qty',
        ),
    ]
