# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20170118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Найменування'),
        ),
    ]
