# ansible-playbook -i hosts deploy.yml -l vagrant_vm -e "ansible_python_interpreter=/usr/bin/python3"

---
- hosts: all
  gather_facts: no
  become: yes

  vars:
    virtualenv_path: '/home/vagrant/virtualenv/env36'
    project_path: '/home/vagrant/warehousedb'
    settings: 'warehousedb.settings.production'

  tasks:
    - name: Update system packages
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - python3-pip
        - python3-dev
        - libpq-dev
        - postgresql
        - postgresql-contrib
        - nginx

    - name: Get repository from GitHub
      git:
        repo: 'https://github.com/samitnuk/warehousedb.git'
        dest: '{{ project_path }}'
        version: 'master'
        accept_hostkey: yes
        force: yes


    - name: Install project requirements
      pip:
        requirements: '{{ project_path }}/requirements.txt'
        virtualenv: '{{ virtualenv_path }}'
        virtualenv_python: python3.6

    - name: Migrate
      django_manage:
        command: migrate
        app_path: '{{ project_path }}'
        settings: '{{ settings }}'
        virtualenv: '{{ virtualenv_path }}'
