# ansible-playbook --private-key=~/.vagrant.d/insecure_private_key -u vagrant -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory ansible/deploy.yaml  -e "ansible_python_interpreter=/usr/bin/python3"

---
- hosts: all

  vars:
    virtualenv_path: 'opt/virtualenvs/env_3.6'
    project_path: 'opt/warehousedb'

  tasks:

    - name: Get repository from GitHub
      git:
        repo: 'https://github.com/samitnuk/warehousedb.git'
        dest: '{{ project_path }}'
        version: 'master'
        accept_hostkey: yes
        force: yes


    - name: Install project requirements
      pip:
        requirements: '{{ project_path }}/requirements.txt'
        virtualenv: '{{ virtualenv_path }}'
        virtualenv_python: python3.6
      become_user: root
